<?php
/*
*--------------------------------------------------------------------------------------------------------------------
*	MODULE NAME: 	GENERAL MODULE
*	DATE WRITTEN:	1-OCT-2015
*	DEVELOPED BY:	ASHLEE MUNSHI
*	REVIEWED BY:	MR. ASHISH NAIK
*	REVIEW DATE:	
*--------------------------------------------------------------------------------------------------------------------
*/


/**
* CITY2SHORE NAVIGATION MENU
*/

function general_menu() {
	
	$items['c2s/user/dashboard'] = array(
		'page callback' => 'c2s_user_dashboard',
        'title'=>'',
        'menu_name' 	=> 'c2s-menu',
		'access callback' => TRUE,
        'access arguments' => array('C2S User Dashboard'),
	);


	return $items;
}

/* -----------------------------------------------------------------------------------*/
// Access Permission
/* -----------------------------------------------------------------------------------*/

/*
function c2s_permission() {
  return array(
      
    'c2s Application' => array(
      'title' => 'c2s Application',
        ),

    'View c2s Application' => array(
      'title' => 'View c2s Application',
        ),
      
    'Delete c2s Application' => array(
      'title' => 'Delete c2s Application',
        ),

    'Employee List c2s Application' => array(
      'title' => 'Employee List c2s Application',
        ),

    'Approval List c2s Application' => array(
      'title' => 'Approval List c2s Application',
        ),

    'Setting c2s' => array(
      'title' => 'Setting c2s',
        ),

    'Delete c2s Setting' => array(
      'title' => 'Delete c2s Setting',
        ),

    'Edit c2s Setting' => array(
      'title' => 'Edit c2s Setting',
        ),

    'Month Wise List c2s' => array(
      'title' => 'Month Wise List c2s',
        ),	  
	  
    'Location Wise List c2s' => array(
      'title' => 'Location Wise List c2s',
        ),

    'Claim List c2s Excess' => array(
      'title' => 'Claim List c2s Excess',
        ),
      
    'Application Details c2s Excess' => array(
      'title' => 'Application Details c2s Excess',
        ),

    'Excess List c2s' => array(
      'title' => 'Excess List c2s',
        ),

    'Subordinate List c2s' => array(
      'title' => 'Subordinate List c2s',
        ),

    'Monthly c2s Application' => array(
      'title' => 'Monthly c2s Application',
        ),

    'Specific c2s Application' => array(
      'title' => 'Specific c2s Application',
        ),

    'View Monthly c2s Application' => array(
      'title' => 'View Monthly c2s Application',
        ),

    'Monthly Approval c2s Application' => array(
      'title' => 'Monthly Approval c2s Application',
        ),	  
		
    'Approval Form Monthly c2s Application' => array(
      'title' => 'Approval Form Monthly c2s Application',
        ),

    'Employee List Monthly c2s Application' => array(
      'title' => 'Employee List Monthly c2s Application',
        ),
      
    'Locationwise List Monthly c2s' => array(
      'title' => 'Locationwise List Monthly c2s',
        ),

    'Monthwise List Monthly c2s' => array(
      'title' => 'Monthwise List Monthly c2s',
        ),

    'Claim List c2s Monthly Excess' => array(
      'title' => 'Claim List c2s Monthly Excess',
        ),
		
   );
}
 
*/

/**
* C2S MANAGEMENT APPLICATION FORM
* This Form is used for Submitting as well as Editing the c2s management Details 
*/
// ==================================================================================================
//                   FORMS INC
// ==================================================================================================


function c2s_user_dashboard() {
	include("page_inc/c2s_user_dashboard.inc");
	return $data;
}


// ==================================================================================================
//                   FORM SUBMITING FUNCTIONS   
// ==================================================================================================


/*
function c2s_setting_submit($form,&$form_state){
		include("submit_inc/c2s_setting_submit.inc"); 
}
*/





