<?php
/*
*--------------------------------------------------------------------------------------------------------------------
*	MODULE NAME: 	BROKER MODULE
*	DATE WRITTEN:	14-SEP-2015
*	DEVELOPED BY:	ASHLEE MUNSHI
*	REVIEWED BY:	MR. ASHISH NAIK
*	REVIEW DATE:	
*--------------------------------------------------------------------------------------------------------------------
*/


/**
* CITY2SHORE NAVIGATION MENU
*/

function broker_menu() {
	
	$items['c2s/broker/add'] = array(
        'title'				=> 'C2S New Broker Enrollment Form',
		'page callback' 	=> 'drupal_get_form',
        'menu_name' 		=> 'c2s-menu',
		'page arguments' 	=> array('c2s_broker_add'),
		'access callback' 	=> TRUE,
        'access arguments' 	=> array('C2S Broker Enrollment Form'),
	);
	
/*	$items['c2s/broker/edit'] = array(
	    'title'				=> 'C2S New Broker Form Edit',
		'page callback' 	=> 'drupal_get_form',
	    'menu_name' 		=> 'c2s-menu',
		'page arguments' 	=> array('c2s_broker_edit'),
		'access callback' 	=> TRUE,
	    'access arguments' 	=> array('C2S Broker Form Edit'),
	);
	*/
	/*
	$items['c2s/broker/view'] = array(
	    'title'				=> 'C2S New Broker View Form',
		'page callback' 	=> 'drupal_get_form',
	    'menu_name' 		=> 'c2s-menu',
		'page arguments' 	=> array('c2s_broker_view'),
		'access callback' 	=> TRUE,
	    'access arguments' 	=> array('C2S Broker View Form'),
	);*/
	
	 $items['c2s/broker/view'] = array(
    'title' => t('C2S New Broker View Form'),
    'page callback' => 'c2s_broker_view',
    'access callback' => TRUE,
  );
  
  	 $items['c2s/broker/list'] = array(
    'title' => t('C2S New Broker List'),
    'page callback' => 'c2s_broker_list',
    'access callback' => TRUE,
  );

	$items['c2s/broker/deactivate'] = array(
        'title'=>'c2s Application Delete',
		'page callback' => 'drupal_get_form',
        'menu_name' 	=> 'c2s-menu',
		'page arguments' => array('c2s_broker_deactivate'),
		'access callback' => TRUE,
        'access arguments' => array('Deactivate C2S Broker'),
	);

	return $items;
}

/* -----------------------------------------------------------------------------------*/
// Access Permission
/* -----------------------------------------------------------------------------------*/

/*
function c2s_permission() {
  return array(
      
    'c2s Application' => array(
      'title' => 'c2s Application',
        ),

    'View c2s Application' => array(
      'title' => 'View c2s Application',
        ),
      
    'Delete c2s Application' => array(
      'title' => 'Delete c2s Application',
        ),

    'Employee List c2s Application' => array(
      'title' => 'Employee List c2s Application',
        ),

    'Approval List c2s Application' => array(
      'title' => 'Approval List c2s Application',
        ),

    'Setting c2s' => array(
      'title' => 'Setting c2s',
        ),

    'Delete c2s Setting' => array(
      'title' => 'Delete c2s Setting',
        ),

    'Edit c2s Setting' => array(
      'title' => 'Edit c2s Setting',
        ),

    'Month Wise List c2s' => array(
      'title' => 'Month Wise List c2s',
        ),	  
	  
    'Location Wise List c2s' => array(
      'title' => 'Location Wise List c2s',
        ),

    'Claim List c2s Excess' => array(
      'title' => 'Claim List c2s Excess',
        ),
      
    'Application Details c2s Excess' => array(
      'title' => 'Application Details c2s Excess',
        ),

    'Excess List c2s' => array(
      'title' => 'Excess List c2s',
        ),

    'Subordinate List c2s' => array(
      'title' => 'Subordinate List c2s',
        ),

    'Monthly c2s Application' => array(
      'title' => 'Monthly c2s Application',
        ),

    'Specific c2s Application' => array(
      'title' => 'Specific c2s Application',
        ),

    'View Monthly c2s Application' => array(
      'title' => 'View Monthly c2s Application',
        ),

    'Monthly Approval c2s Application' => array(
      'title' => 'Monthly Approval c2s Application',
        ),	  
		
    'Approval Form Monthly c2s Application' => array(
      'title' => 'Approval Form Monthly c2s Application',
        ),

    'Employee List Monthly c2s Application' => array(
      'title' => 'Employee List Monthly c2s Application',
        ),
      
    'Locationwise List Monthly c2s' => array(
      'title' => 'Locationwise List Monthly c2s',
        ),

    'Monthwise List Monthly c2s' => array(
      'title' => 'Monthwise List Monthly c2s',
        ),

    'Claim List c2s Monthly Excess' => array(
      'title' => 'Claim List c2s Monthly Excess',
        ),
		
   );
}
 
*/

/**
* C2S MANAGEMENT APPLICATION FORM
* This Form is used for Submitting as well as Editing the c2s management Details 
*/
// ==================================================================================================
//                   FORMS INC
// ==================================================================================================

function c2s_broker_add($form, &$form_state) {
//	include("../support/inc/add_js.inc"); 
	include("form_inc/c2s_broker_add.inc");
	return $form;
}

function c2s_broker_edit($form, &$form_state) {
//	include("../support/inc/add_js.inc"); 
	include("form_inc/c2s_broker_edit.inc");
	return $form;
}

function c2s_broker_view($form, &$form_state) {
//	include("form_inc/c2s_broker_view.inc");
//	return $form;
$brokerage_id = arg(3);
  $build = array();

  $build['form_one'] = drupal_get_form('c2s_brokerage_edit_view');
  
  $result = db_query("SELECT broker_agent_id FROM broker_master WHERE brokerage_id = ".$brokerage_id." and deactivate = 0");
$broker_id = array();
$n=0;
  foreach($result as $value){
  $n++;
  $broker_id[$n] = $value->broker_agent_id;
  }
  $total_brokers = $n;
  for($i=1; $i<=$total_brokers; $i++){
  	$build['form_'.$i] = drupal_get_form('c2s_broker_edit_view',$broker_id[$i],$i);
  }
  return $build;

}

function c2s_broker_edit_view($form, &$form_state,$var,$i){
	$form_state['broker_id'] = $var;
	$form_state['form_id'] = $i;
	include("form_inc/c2s_broker_view.inc");
	return $form;
}



function c2s_brokerage_edit_view($form, &$form_state){
	include("form_inc/c2s_brokerage-edit-view.inc");
	return $form;
}



function c2s_broker_list() {
	include("page_inc/c2s_broker_list.inc");
	return $data;
}

/*
function c2s_application_approver_list($form, &$form_state) {
	include("form_inc/c2s_application_approver_list.inc");
	return $form;
}

function c2s_setting($form, &$form_state) {
   include("form_inc/c2s_setting.inc");
   return $form;
}

function edit_ot_setting($form, &$form_state) {
   include("form_inc/edit_ot_setting.inc");
   return $form;
}

function c2s_month_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_month_wise_list.inc");
   return $form;
}

function c2s_location_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_location_wise_list.inc");
   return $form;
}

function c2s_excess_claims_list($form, &$form_state) {
   include("form_inc/c2s_monthly_excess_claims_list.inc");
   return $form;
}

function excess_c2s_application_details($form, &$form_state) {
   include("form_inc/excess_c2s_application_details.inc");
   return $form;
}
function excess_c2s_list($form, &$form_state) {
   include("form_inc/excess_c2s_list.inc");
   return $form;
}
function subordinate_c2s_list($form, &$form_state) {
   include("form_inc/subordinate_c2s_list.inc");
   return $form;
}
function c2s_application_monthly($form, &$form_state) {
   include("form_inc/c2s_application_monthly.inc");
   return $form;
}
function specific_c2s_application($form, &$form_state) {
   include("form_inc/specific_c2s_application.inc");
   return $form;
}
function c2s_application_monthly_view($form, &$form_state) {
   include("form_inc/c2s_application_monthly_view.inc");
   return $form;
}
function c2s_application_monthly_approver_list($form, &$form_state) {
   include("form_inc/c2s_application_monthly_approver_list.inc");
   return $form;
}
function c2s_application_monthly_approver_form($form, &$form_state) {
   include("form_inc/c2s_application_monthly_approver_form.inc");
   return $form;
}
function c2s_application_monthly_employee_list($form, &$form_state) {
   include("form_inc/c2s_application_monthly_employee_list.inc");
   return $form;
}
function c2s_monthly_location_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_location_wise_list.inc");
   return $form;
}
function c2s_monthly_month_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_month_wise_list.inc");
   return $form;
}
function c2s_monthly_excess_claims_list($form, &$form_state) {
   include("form_inc/c2s_monthly_excess_claims_list.inc");
   return $form;
}
*/
// ==================================================================================================
//                   FORM SUBMITING FUNCTIONS   
// ==================================================================================================

function c2s_broker_add_submit($form,&$form_state){
		include("submit_inc/broker_add_submit.inc"); 
}
/*
function c2s_setting_submit($form,&$form_state){
		include("submit_inc/c2s_setting_submit.inc"); 
}
function c2s_application_monthly_submit($form,&$form_state){
		include("submit_inc/c2s_application_monthly_submit.inc"); 
}

function c2s_application_specific_submit($form,&$form_state){
		include("submit_inc/c2s_application_specific_submit.inc"); 
}
function c2s_application_monthly_approver_submit($form,&$form_state){
		include("submit_inc/c2s_application_monthly_approver_submit.inc"); 
}
*/
// ==================================================================================================
//  				ALL FUNCTION c2s MANAGEMENT IN FUNCTIONS INC 
// ==================================================================================================
//include("func_inc/c2s_functions.inc"); 
// --------------------------------------------------------------------------------------------------
  //include("func_inc/workflow.inc"); 
// --------------------------------------------------------------------------------------------------


// ==================================================================================================
//  				ADD MORE FUNCTIONS
// ==================================================================================================


function spower_add_more_callback($form, $form_state) {
  return $form['names_fieldset'];
}
function spower_add_more_callback_tabs($form, $form_state) {
  return $form['names_fieldset_tabs'];
}

/**
 * Submit handler for the "add-one-more" button.
 *
 * Increments the max counter and causes a rebuild.
 */
function spower_add_more_add_one($form, &$form_state) {
  $form_state['num_names']++;
  drupal_set_message($form_state['num_names']);
  $form_state['rebuild'] = TRUE;
}

/**
 * Submit handler for the "remove one" button.
 *
 * Decrements the max counter and causes a form rebuild.
 */
function spower_add_more_remove_one($form, &$form_state) {
  if ($form_state['num_names'] > 1) {
    $form_state['num_names']--;
  }
  $form_state['rebuild'] = TRUE;
}
