<?php

drupal_add_css( drupal_get_path('module', 'broker') . '/css/global-c2s.css');




     $data  =  "";
	 
	 $data .=  '<div class="content" style="background-color:#ebeff2 !important"> &nbsp; '; // Section Start
	 
	 $data .=  '<img src="'.base_path().'/'.drupal_get_path('module', 'general').'/images/dashboard_top.png" >';
	 $data .=  '<img src="'.base_path().'/'.drupal_get_path('module', 'general').'/images/dashboard_bottom.png">';

	 $data .=  '</div> '; // Section End
	 $data .=  '</div> '; // Section End
	 $data .=  '</div> '; // Wrapper End
	