<?php
/*
*--------------------------------------------------------------------------------------------------------------------
*	MODULE NAME: 	AGENT MODULE
*	DATE WRITTEN:	14-SEP-2015
*	DEVELOPED BY:	ASHLEE MUNSHI
*	REVIEWED BY:	MR. ASHISH NAIK
*	REVIEW DATE:	
*--------------------------------------------------------------------------------------------------------------------
*/


/**
* CITY2SHORE NAVIGATION MENU
*/

function agent_menu() {
	
	$items['c2s/agent/add'] = array(
        'title'				=> 'C2S New Agent Enrollment Form',
		'page callback' 	=> 'drupal_get_form',
        'menu_name' 		=> 'c2s-menu',
		'page arguments' 	=> array('c2s_agent_add'),
		'access callback' 	=> TRUE,
        'access arguments' 	=> array('C2S Agent Enrollment Form'),
	);
	
	$items['c2s/agent/view'] = array(
		'page callback' => 'drupal_get_form',
        'title'=>'C2S Agent Profile View',
        'menu_name' 	=> 'c2s-menu',
		'page arguments' => array('c2s_agent_view'),
		'access callback' => TRUE,
        'access arguments' => array('C2S Agent Profile View'),
	);
	
	$items['c2s/agent/list'] = array(
    'title' => t('C2S New Broker List'),
    'page callback' => 'c2s_agent_list',
    'access callback' => TRUE,
  	);

	$items['c2s/agent/delete'] = array(
        'title'=>'C2S Application Delete',
		'page callback' => 'drupal_get_form',
        'menu_name' 	=> 'c2s-menu',
		'page arguments' => array('c2s_agent_delete'),
		'access callback' => TRUE,
        'access arguments' => array('Delete C2S Agent'),
	);

	return $items;
}

/* -----------------------------------------------------------------------------------*/
// Access Permission
/* -----------------------------------------------------------------------------------*/

/*
function c2s_permission() {
  return array(
      
    'c2s Application' => array(
      'title' => 'c2s Application',
        ),

    'View c2s Application' => array(
      'title' => 'View c2s Application',
        ),
      
    'Delete c2s Application' => array(
      'title' => 'Delete c2s Application',
        ),

    'Employee List c2s Application' => array(
      'title' => 'Employee List c2s Application',
        ),

    'Approval List c2s Application' => array(
      'title' => 'Approval List c2s Application',
        ),

    'Setting c2s' => array(
      'title' => 'Setting c2s',
        ),

    'Delete c2s Setting' => array(
      'title' => 'Delete c2s Setting',
        ),

    'Edit c2s Setting' => array(
      'title' => 'Edit c2s Setting',
        ),

    'Month Wise List c2s' => array(
      'title' => 'Month Wise List c2s',
        ),	  
	  
    'Location Wise List c2s' => array(
      'title' => 'Location Wise List c2s',
        ),

    'Claim List c2s Excess' => array(
      'title' => 'Claim List c2s Excess',
        ),
      
    'Application Details c2s Excess' => array(
      'title' => 'Application Details c2s Excess',
        ),

    'Excess List c2s' => array(
      'title' => 'Excess List c2s',
        ),

    'Subordinate List c2s' => array(
      'title' => 'Subordinate List c2s',
        ),

    'Monthly c2s Application' => array(
      'title' => 'Monthly c2s Application',
        ),

    'Specific c2s Application' => array(
      'title' => 'Specific c2s Application',
        ),

    'View Monthly c2s Application' => array(
      'title' => 'View Monthly c2s Application',
        ),

    'Monthly Approval c2s Application' => array(
      'title' => 'Monthly Approval c2s Application',
        ),	  
		
    'Approval Form Monthly c2s Application' => array(
      'title' => 'Approval Form Monthly c2s Application',
        ),

    'Employee List Monthly c2s Application' => array(
      'title' => 'Employee List Monthly c2s Application',
        ),
      
    'Locationwise List Monthly c2s' => array(
      'title' => 'Locationwise List Monthly c2s',
        ),

    'Monthwise List Monthly c2s' => array(
      'title' => 'Monthwise List Monthly c2s',
        ),

    'Claim List c2s Monthly Excess' => array(
      'title' => 'Claim List c2s Monthly Excess',
        ),
		
   );
}
 
*/

/**
* C2S MANAGEMENT APPLICATION FORM
* This Form is used for Submitting as well as Editing the c2s management Details 
*/
// ==================================================================================================
//                   FORMS INC
// ==================================================================================================

function c2s_agent_add($form, &$form_state) {
//	include("../support/inc/add_js.inc"); 
	include("form_inc/c2s_agent_add.inc");
	return $form;
}
function c2s_agent_view($form, &$form_state) {
	include("form_inc/c2s_agent_view.inc");
	return $form;
}

function c2s_agent_delete($form, &$form_state) {
	include("form_inc/c2s_agent_delete.inc");
	return $form;
}

function c2s_agent_list() {
	include("page_inc/c2s_agent_list.inc");
	return $data;
}

/*
function c2s_application_approver_list($form, &$form_state) {
	include("form_inc/c2s_application_approver_list.inc");
	return $form;
}

function c2s_setting($form, &$form_state) {
   include("form_inc/c2s_setting.inc");
   return $form;
}

function edit_ot_setting($form, &$form_state) {
   include("form_inc/edit_ot_setting.inc");
   return $form;
}

function c2s_month_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_month_wise_list.inc");
   return $form;
}

function c2s_location_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_location_wise_list.inc");
   return $form;
}

function c2s_excess_claims_list($form, &$form_state) {
   include("form_inc/c2s_monthly_excess_claims_list.inc");
   return $form;
}

function excess_c2s_application_details($form, &$form_state) {
   include("form_inc/excess_c2s_application_details.inc");
   return $form;
}
function excess_c2s_list($form, &$form_state) {
   include("form_inc/excess_c2s_list.inc");
   return $form;
}
function subordinate_c2s_list($form, &$form_state) {
   include("form_inc/subordinate_c2s_list.inc");
   return $form;
}
function c2s_application_monthly($form, &$form_state) {
   include("form_inc/c2s_application_monthly.inc");
   return $form;
}
function specific_c2s_application($form, &$form_state) {
   include("form_inc/specific_c2s_application.inc");
   return $form;
}
function c2s_application_monthly_view($form, &$form_state) {
   include("form_inc/c2s_application_monthly_view.inc");
   return $form;
}
function c2s_application_monthly_approver_list($form, &$form_state) {
   include("form_inc/c2s_application_monthly_approver_list.inc");
   return $form;
}
function c2s_application_monthly_approver_form($form, &$form_state) {
   include("form_inc/c2s_application_monthly_approver_form.inc");
   return $form;
}
function c2s_application_monthly_employee_list($form, &$form_state) {
   include("form_inc/c2s_application_monthly_employee_list.inc");
   return $form;
}
function c2s_monthly_location_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_location_wise_list.inc");
   return $form;
}
function c2s_monthly_month_wise_list($form, &$form_state) {
   include("form_inc/c2s_monthly_month_wise_list.inc");
   return $form;
}
function c2s_monthly_excess_claims_list($form, &$form_state) {
   include("form_inc/c2s_monthly_excess_claims_list.inc");
   return $form;
}
*/
// ==================================================================================================
//                   FORM SUBMITING FUNCTIONS   
// ==================================================================================================

function c2s_agent_add_submit($form,&$form_state){
		include("submit_inc/agent_add_submit.inc"); 
}
function c2s_agent_view_submit($form,&$form_state){
		include("submit_inc/c2s_agent_update.inc"); 
}
/*
function c2s_setting_submit($form,&$form_state){
		include("submit_inc/c2s_setting_submit.inc"); 
}
function c2s_application_monthly_submit($form,&$form_state){
		include("submit_inc/c2s_application_monthly_submit.inc"); 
}

function c2s_application_specific_submit($form,&$form_state){
		include("submit_inc/c2s_application_specific_submit.inc"); 
}
function c2s_application_monthly_approver_submit($form,&$form_state){
		include("submit_inc/c2s_application_monthly_approver_submit.inc"); 
}
*/
// ==================================================================================================
//  				ALL FUNCTION c2s MANAGEMENT IN FUNCTIONS INC 
// ==================================================================================================
//include("func_inc/c2s_functions.inc"); 
// --------------------------------------------------------------------------------------------------
  //include("func_inc/workflow.inc"); 
// --------------------------------------------------------------------------------------------------



/// ---------

function c2s_agent_add_validate($form, &$form_state) {
    $agent_relationship = $form_state['values']['agent_relationship'];
    $i = 2;
if($agent_relationship!=0){
$broker[$i]['first_name']			=   $form_state['values']['agent_'.$i.'_first_name'];
$broker[$i]['middle_name']			=   $form_state['values']['agent_'.$i.'_middle_name'];
$broker[$i]['last_name']		    =   $form_state['values']['agent_'.$i.'_last_name'];

$broker[$i]['dob']				    =   $form_state['values']['date_of_birth_'.$i];
$broker[$i]['personal_email']		=   $form_state['values']['personl_email_id_'.$i];
$broker[$i]['personal_phone']		=   $form_state['values']['contact_number_'.$i];
$broker[$i]['home_address']			=   $form_state['values']['street_address_'.$i];
$broker[$i]['home_city']			=   $form_state['values']['city_id_'.$i];
$broker[$i]['home_state']			=   $form_state['values']['state_id_'.$i];
$broker[$i]['home_zip']			    =   $form_state['values']['zip_code_'.$i];
$broker[$i]['state_id_number']		=   $form_state['values']['agent_state_id_'.$i];
$broker[$i]['mls_username']			=   $form_state['values']['mls_username_'.$i];
$broker[$i]['mls_password']			=   $form_state['values']['mls_password_'.$i];
$broker[$i]['nrds_number']			=   $form_state['values']['agent_nrds_'.$i];
$broker[$i]['c2s_email_id']			=   $form_state['values']['create_email_'.$i];
$broker[$i]['office_phone']			=   $form_state['values']['office_phone_'.$i];
$broker[$i]['office_extension']		=   $form_state['values']['extension_'.$i];
$broker[$i]['choice_charity_orgid']	=   $form_state['values']['choice_of_charity_org_'.$i];
// -----///
$broker[$i]['pers_comm_accno']		=   $form_state['values']['personal_account_number_'.$i];
$broker[$i]['pers_comm_accname']	=   $form_state['values']['name_on_personal_account_'.$i];
$broker[$i]['pers_comm_bankname']	=   $form_state['values']['personal_financial_institution_name_'.$i];
$broker[$i]['pers_comm_bankphone']	=   $form_state['values']['personal_financial_institution_phone_'.$i];
$broker[$i]['pers_comm_acctype']	=   $form_state['values']['personal_account_type_'.$i];
$broker[$i]['pers_comm_aba_routing']=   $form_state['values']['personal_aba_routing_number_'.$i];
// ------ //

 if($broker[$i]['first_name'] == "") {
        form_set_error('agent_'.$i.'_first_name', 'Agent Two : Please enter a valid first name');
    }
 if($broker[$i]['middle_name'] == "") {
        form_set_error('agent_'.$i.'_middle_name', 'Agent Two : Please enter a valid middle name');
    }
 if($broker[$i]['last_name'] == "") {
        form_set_error('agent_'.$i.'_last_name', 'Agent Two : Please enter a valid last name');
    }
 if($broker[$i]['dob'] == "") {
        form_set_error('date_of_birth_'.$i, 'Agent Two : Please enter a valid date of birth');
    }
 if($broker[$i]['personal_email'] == "") {
        form_set_error('personl_email_id_'.$i, 'Agent Two : Please enter a valid email id');
    }
 if($broker[$i]['personal_phone'] == "") {
        form_set_error('contact_number_'.$i, 'Agent Two : Please enter a valid contact number');
    }
 if($broker[$i]['home_address'] == "") {
        form_set_error('street_address_'.$i, 'Agent Two : Please enter a valid street address');
    }
 if($broker[$i]['home_city'] == "0") {
        form_set_error('city_id_'.$i, 'Agent Two : Please select a valid city');
    }
 if($broker[$i]['home_state'] == "") {
        form_set_error('state_id_'.$i, 'Agent Two : Please select a valid state');
    }
 if($broker[$i]['home_zip'] == "") {
        form_set_error('zip_code_'.$i, 'Agent Two : Please enter a valid zip code');
    }
    // ------------
 if($broker[$i]['state_id_number'] == "") {
        form_set_error('agent_state_id_number_'.$i, 'Agent Two : Please enter a valid state id number');
    }
 if($broker[$i]['nrds_number'] == "") {
        form_set_error('agent_nrds_'.$i, 'Agent Two : Please enter a valid nrds number');
    }
 if($broker[$i]['mls_username'] == "") {
        form_set_error('mls_username_'.$i, 'Agent Two : Please enter a valid mls username');
    }
 if($broker[$i]['mls_password'] == "") {
        form_set_error('mls_password_'.$i, 'Agent Two : Please enter a valid mls password');
    }
 if($broker[$i]['office_phone'] == "") {
        form_set_error('office_phone_'.$i, 'Agent Two : Please enter a valid street address');
    }
 if($broker[$i]['office_extension'] == "0") {
        form_set_error('extension_'.$i, 'Agent Two : Please select a valid city');
    }
 if($broker[$i]['c2s_email_id'] == "") {
        form_set_error('create_email_'.$i, 'Agent Two : Please enter a valid state id number');
    }
 if($broker[$i]['choice_charity_orgid'] == "") {
        form_set_error('choice_of_charity_org_'.$i, 'Agent Two : Please enter a valid nrds number');
    }
 if($broker[$i]['pers_comm_accno'] == "") {
        form_set_error('personal_account_number_'.$i, 'Agent Two : Please enter a valid mls username');
    }
 if($broker[$i]['pers_comm_accname'] == "") {
        form_set_error('name_on_personal_account_'.$i, 'Agent Two : Please enter a valid mls password');
    }
 if($broker[$i]['pers_comm_bankname'] == "") {
        form_set_error('personal_financial_institution_name_'.$i, 'Agent Two : Please enter a valid street address');
    }
 if($broker[$i]['pers_comm_bankphone'] == "0") {
        form_set_error('personal_financial_institution_phone_'.$i, 'Agent Two : Please select a valid city');
    }
 if($broker[$i]['pers_comm_accname'] == "") {
        form_set_error('personal_account_type_'.$i, 'Agent Two : Please enter a valid mls password');
    }
 if($broker[$i]['pers_comm_bankname'] == "") {
        form_set_error('personal_aba_routing_number_'.$i, 'Agent Two : Please enter a valid street address');
    }
 if($broker[$i]['pers_comm_bankphone'] == "0") {
        form_set_error('personal_financial_institution_phone_'.$i, 'Agent Two : Please select a valid city');
    }
 
}
   
}
