<?php
/*
*--------------------------------------------------------------------------------------------------------------------
*	MODULE NAME: 	CHARITY MODULE
*	DATE WRITTEN:	14-SEP-2015
*	DEVELOPED BY:	ASHLEE MUNSHI
*	REVIEWED BY:	MR. ASHISH NAIK
*	REVIEW DATE:	
*--------------------------------------------------------------------------------------------------------------------
*/


/**
* CITY2SHORE CHARITY MODULE NAVIGATION MENU
*/

function charity_menu() {
	
	$items['c2s/charity/add'] = array(
        'title'				=> 'New Charity Enrollment Form',
		'page callback' 	=> 'drupal_get_form',
        'menu_name' 		=> 'c2s-menu',
		'page arguments' 	=> array('c2s_charity_add'),
		'access callback' 	=> TRUE,
        'access arguments' 	=> array('Charity Enrollment Form'),
	);
	
	$items['c2s/charity/view'] = array(
        'title'=>'Charity Profile View',
        'menu_name' 	=> 'c2s-menu',
		'page callback' => 'c2s_charity_view',
		'access callback' => TRUE,
        'access arguments' => array('Charity Profile View'),
	);

	$items['c2s/charity/deactivate'] = array(
        'title'				=> 'Charity Organization Deactivate',
		'page callback' 	=> 'drupal_get_form',
        'menu_name' 		=> 'c2s-menu',
		'page arguments' 	=> array('c2s_charity_deactivate'),
		'access callback' 	=> TRUE,
        'access arguments' 	=> array('Delete C2S Charity'),
	);

	$items['c2s/charity/list'] = array(
        'title'			=>	'Charity Profile List',
        'menu_name' 	=> 	'c2s-menu',
		'page callback' => 'c2s_charity_list',
		'access callback' 	=> TRUE,
        'access arguments' 	=> array('Charity Profile List'),
	);

	return $items;
}

/* -----------------------------------------------------------------------------------*/
// Access Permission
/* -----------------------------------------------------------------------------------*/

/*
function c2s_permission() {
  return array(
      
    'c2s Application' => array(
      'title' => 'c2s Application',
        ),

    'View c2s Application' => array(
      'title' => 'View c2s Application',
        ),
      
    'Delete c2s Application' => array(
      'title' => 'Delete c2s Application',
        ),

    'Employee List c2s Application' => array(
      'title' => 'Employee List c2s Application',
        ),

    'Approval List c2s Application' => array(
      'title' => 'Approval List c2s Application',
        ),

    'Setting c2s' => array(
      'title' => 'Setting c2s',
        ),

    'Delete c2s Setting' => array(
      'title' => 'Delete c2s Setting',
        ),

    'Edit c2s Setting' => array(
      'title' => 'Edit c2s Setting',
        ),

    'Month Wise List c2s' => array(
      'title' => 'Month Wise List c2s',
        ),	  
	  
    'Location Wise List c2s' => array(
      'title' => 'Location Wise List c2s',
        ),

    'Claim List c2s Excess' => array(
      'title' => 'Claim List c2s Excess',
        ),
      
    'Application Details c2s Excess' => array(
      'title' => 'Application Details c2s Excess',
        ),

    'Excess List c2s' => array(
      'title' => 'Excess List c2s',
        ),

    'Subordinate List c2s' => array(
      'title' => 'Subordinate List c2s',
        ),

    'Monthly c2s Application' => array(
      'title' => 'Monthly c2s Application',
        ),

    'Specific c2s Application' => array(
      'title' => 'Specific c2s Application',
        ),

    'View Monthly c2s Application' => array(
      'title' => 'View Monthly c2s Application',
        ),

    'Monthly Approval c2s Application' => array(
      'title' => 'Monthly Approval c2s Application',
        ),	  
		
    'Approval Form Monthly c2s Application' => array(
      'title' => 'Approval Form Monthly c2s Application',
        ),

    'Employee List Monthly c2s Application' => array(
      'title' => 'Employee List Monthly c2s Application',
        ),
      
    'Locationwise List Monthly c2s' => array(
      'title' => 'Locationwise List Monthly c2s',
        ),

    'Monthwise List Monthly c2s' => array(
      'title' => 'Monthwise List Monthly c2s',
        ),

    'Claim List c2s Monthly Excess' => array(
      'title' => 'Claim List c2s Monthly Excess',
        ),
		
   );
}
 
*/

/**
* C2S MANAGEMENT APPLICATION FORM
* This Form is used for Submitting as well as Editing the c2s management Details 
*/
// ==================================================================================================
//                   FORMS INC
// ==================================================================================================

function c2s_charity_add($form, &$form_state) {
	include("form_inc/c2s_charity_add.inc");
	return $form;
}
function c2s_charity_view() {
	include("form_inc/c2s_charity_view.inc");
	return $output;
}
function c2s_charity_deactivate($form, &$form_state) {
	include("form_inc/c2s_charity_deactivate.inc");
	return $form;
}

function c2s_charity_list() {
	include("form_inc/c2s_charity_list.inc");
	return $output;
}

// ==================================================================================================
//                   FORM SUBMITING FUNCTIONS   
// ==================================================================================================

function c2s_charity_add_submit($form,&$form_state){
		include("submit_inc/charity_add_submit.inc"); 
}
function c2s_charity_view_edit_submit($form,&$form_state){
		include("submit_inc/charity_view_edit_submit.inc"); 
}

// ==================================================================================================
//                   AJAX   
// ==================================================================================================

function find_cities_callback($form, $form_state) {
	return $form['city'];
}

function find_zip_callback($form, $form_state) {
	return $form['zip_code'];
}

function getStates(){
	$state_options = array();
	$state_options[] = '-- Select --';
	$result_state = db_query("SELECT state, state_code FROM states ORDER BY 1");
	foreach($result_state as $value){
		$state_options[$value->state_code]	=	$value->state;
	}
	
	return $state_options;
}

function getCities($state_code){
	$city_options = array();
	$city_options[] = '-- Select --';
	$result_city = db_query("SELECT city FROM cities_extended WHERE state_code = '".$state_code ."' ORDER BY 1");
	foreach($result_city as $value){
		$city_options[$value->city]	=	$value->city;
	}
	return $city_options;
}

function getZip($city, $state_code){
	$zip = '';
	$result_zip = db_query("SELECT zip FROM cities_extended WHERE state_code = '".$state_code ."' AND city = '".$city."' ORDER BY 1" );
	foreach($result_zip as $value){
		$zip	=	$value->zip;
	}
	return $zip;
}










